### ISSUE TITLE
node not installed on the Vagrant box

### ISSUE THREAD

**Issue by ctford** [ThoughtWorksInc/objective8#10]
In order to run the unit tests, you need to build the assets. In order to build the assets, you need node.

I found these instructions, as the apt-get package caused node-sass to fail:

https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions

**Comment by robinweston** [comment]
Worked fine for me. I can see the nodejs install task at line 8 of **ops\roles\dev\tasks\main.yaml**

````
 - name: install node.js
   apt: name=nodejs state=present
````

**Comment by duncanmortimer** [comment]
Looks like this is ok.  Will close.
