### ISSUE TITLE
Incorrect Error Message for Add Questions Pop-Up Box

### ISSUE THREAD

**Issue by jieselle** [ThoughtWorksInc/objective8#3]
User goes to the website, clicks on any created - Objective, scrolls down to 'Recently Asked Questions', clicks on the "Add Question" button at the bottom of the page

If the box where the comments are suppose to added is left empty and the user clicks on the button below the box  - 'Add Questions', the pop-up box which shows the error message, is incorrect. 
It shows:
     'Please fill out this field '!Textarea title' instead of 'Please fill out this field'.

**Comment by elrob** [comment]
4ae2c43b207a2cdb7c9c8300ae966da9b754ffd2
Fixed
