### ISSUE TITLE
npm not installed on the Vagrant box

### ISSUE THREAD

**Issue by ctford** [ThoughtWorksInc/objective8#5]
The instructions for getting started involve an `npm install`, but npm isn't there.

**Comment by robinweston** [comment]
Worked fine for me. I can see the NPM install task at line 14 of **ops\roles\dev\tasks\main.yaml**

````
- name: install npm
   apt: name=npm state=present
````

**Comment by duncanmortimer** [comment]
Looks like this is ok.  Will close.
