### ISSUE TITLE
lein not installed on the Vagrant box

### ISSUE THREAD

**Issue by ctford** [ThoughtWorksInc/objective8#6]
The instructions for migration and running the tests involve `lein`, but it's not there.

**Comment by robinweston** [comment]
Worked fine for me. Lein was downloaded when I first tried to use it. See output below:

vagrant@vagrant-ubuntu-trusty-64:/var/objective8$ lein
Downloading Leiningen to /home/vagrant/.lein/self-installs/leiningen-2.5.1-standalone.jar now...

**Comment by ctford** [comment]
Oh, that's good.

Maybe my Ansible run failed?

**Comment by duncanmortimer** [comment]
Looks like this is ok.  Will close.
